-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jul 03, 2013 at 08:40 AM
-- Server version: 5.5.27
-- PHP Version: 5.4.7

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE IF NOT EXISTS `blog` (
  `blogid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `title` text NOT NULL,
  `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `status` int(11) NOT NULL,
  `blogdetail` text,
  PRIMARY KEY (`blogid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=16 ;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`blogid`, `username`, `title`, `date`, `status`, `blogdetail`) VALUES
(4, 'basti', 'linux', '2013-06-26 08:33:41', 0, 'Modules add functionality to your Drupal site. The core installation of Drupal includes several modules which are known as core modules. There are several key core modules that you should consider enabling on any Drupal-powered website. A list of the core modules that I recommend activating for most basic sites follows.'),
(5, 'basti', 'yash', '2013-06-26 08:46:43', 0, 'iiitm\r\ngwalior'),
(6, 'pankaj', 'genx', '2013-06-27 10:36:14', 0, 'hello\r\ni am woking with genx soft company\r\n'),
(7, 'pankaj', 'iiitm', '2013-06-27 10:51:05', 0, 'I am Pankaj Chaudhary\r\nI am doing B.tech+M.tech form Indian institute of information technolgoy and management gwalior.'),
(8, 'pankaj', 'iiitm', '2013-06-27 10:51:48', 0, 'I am Pankaj Chaudhary\r\nI am doing B.tech+M.tech form Indian institute of information technolgoy and management gwalior.'),
(9, 'yash', 'web developer', '2013-06-27 20:01:16', 0, 'requirement for webdeveloper\r\nHTML\r\nCSS\r\nJava script\r\nphp\r\nJSP\r\nmysql database'),
(10, 'pankaj', 'DBMS', '2013-06-28 08:55:14', 0, 'right-hand side relation, and adds them to the result. Similarly, it extends with\r\nnulls those tuples from the right-hand-side relation that did not match with any\r\ntuples from the left-hand-side relation and adds them to the result.\r\nAs an example of the use of full outer join, consider the following query:\r\nâ??Display a list of all students in the Comp. Sci. department, along with the course\r\nsections, if any, that they have taken in Spring 2009; all course sections fromSpring\r\n2009 must be displayed, even if no student from the Comp. Sci. department has\r\ntaken the course section.â?? This query can be written as:\r\nright-hand side relation, and adds them to the result. Similarly, it extends with\r\nnulls those tuples from the right-hand-side relation that did not match with any\r\ntuples from the left-hand-side relation and adds them to the result.\r\nAs an example of the use of full outer join, consider the following query:\r\nâ??Display a list of all students in the Comp. Sci. department, along with the course\r\nsections, if any, that they have taken in Spring 2009; all course sections fromSpring\r\n2009 must be displayed, even if no student from the Comp. Sci. department has\r\ntaken the course section.â?? This query can be written as:'),
(11, 'pankaj', 'DBMS', '2013-06-28 09:04:02', 0, 'The earlier query, using the left outer join with the on condition, includes a tuple\r\n(70557, Snow, Physics, 0, null, null, null, null, null, null ), because there is no tuple\r\nin takes with ID = 70557. In the latter query, however, every tuple satisfies the join\r\ncondition true, so no null-padded tuples are generated by the outer join. The outer\r\njoin actually generates the Cartesian product of the two relations. Since there is\r\nno tuple in takes with ID = 70557, every time a tuple appears in the outer join with\r\nname = â??Snowâ??, the values for student.ID and takes.ID must be different, and such\r\ntuples would be eliminated by the where clause predicate. Thus student Snow\r\nnever appears in the result of the latter query.\r\nThe earlier query, using the left outer join with the on condition, includes a tuple\r\n(70557, Snow, Physics, 0, null, null, null, null, null, null ), because there is no tuple\r\nin takes with ID = 70557. In the latter query, however, every tuple satisfies the join\r\ncondition true, so no null-padded tuples are generated by the outer join. The outer\r\njoin actually generates the Cartesian product of the two relations. Since there is\r\nno tuple in takes with ID = 70557, every time a tuple appears in the outer join with\r\nname = â??Snowâ??, the values for student.ID and takes.ID must be different, and such\r\ntuples would be eliminated by the where clause predicate. Thus student Snow\r\nnever appears in the result of the latter query.'),
(12, 'kissor', 'linux', '2013-06-28 16:12:13', 0, 'How It Works\r\nThe variable myvar is created and assigned the string Hi there. The contents of the variable are displayed\r\nwith the echo command, showing how prefacing the variable with a $ character expands the\r\ncontents of the variable. You see that using double quotes doesnâ??t affect the substitution of the variable,\r\nwhile single quotes and the backslash do. You also use the read command to get a string from the user.\r\nEnvironment Variables\r\nWhen a shell script starts, some variables are initialized from values in the environment. These are normally\r\nin all uppercase form to distinguish them from user-defined (shell) variables in scripts, which are\r\nconventionally lowercase. The variables created depend on your personal configuration. Many are listed\r\nin the manual pages, but the principal ones are listed in the following table:'),
(13, 'kissor', 'linux', '2013-06-28 16:15:44', 0, 'How It Works\r\nThe variable myvar is created and assigned the string Hi there. The contents of the variable are displayed\r\nwith the echo command, showing how prefacing the variable with a $ character expands the\r\ncontents of the variable. You see that using double quotes doesnâ??t affect the substitution of the variable,\r\nwhile single quotes and the backslash do. You also use the read command to get a string from the user.\r\nEnvironment Variables\r\nWhen a shell script starts, some variables are initialized from values in the environment. These are normally\r\nin all uppercase form to distinguish them from user-defined (shell) variables in scripts, which are\r\nconventionally lowercase. The variables created depend on your personal configuration. Many are listed\r\nin the manual pages, but the principal ones are listed in the following table:'),
(14, 'yash', 'DBMS', '2013-07-01 04:12:53', 0, 'DBMS\r\nright-hand side relation, and adds them to the result. Similarly, it extends with nulls those tuples from the right-hand-side relation that did not match with any tuples from the left-hand-side relation and adds them to the result. As an example of the use of full outer join, consider the following query: Ã¢??Display a list of all students in the Comp. Sci. department, along with the course sections, if any, that they have taken in Spring 2009; all course sections fromSpring 2009 must be displayed, even if no student from the Comp. Sci. department has taken the course section.Ã¢?? This query can be written as: right-hand side relation, and adds them to the result. Similarly, it extends with nulls those tuples from the right-hand-side relation that did not match with any tuples from the left-hand-side relation and adds them to the result. As an example of the use of full outer join, consider the following query: Ã¢??Display a list of all students in the Comp. Sci. department, along with the course sections, if any, that they have taken in Spring 2009; all course sections fromSpring 2009 must be displayed, even if no student from the Comp. Sci. department has taken the course section.Ã¢?? This query can be written as: '),
(15, 'yash', 'hello', '2013-07-02 17:21:38', 0, 'Ã?ekad % foKkiu la-& 02@ijh{kk@2013&14 fnukad % 18-06-2013\r\n1- vk;ksx }kjk fuEufyf[kr inksa gsrq vkWuykbu vkosnu vkeaf=r fd, tkrs gSa&\r\njktLFkku jkT; ,oa v/khuLFk lsok,a Â¼la;qDr izfr;ksxh ijh{kk }kjk lh/kh HkrhZÂ½ fu;e] 1999 ds vUrxZr jktLFkku jkT; ,oa v/khuLFk lsok,a la;qDr izfr;ksxh ijh{kk] 2013 ds fy;s dkfeZd foHkkx }kjk lwfpr inksa gsrq vkWu ykbu vkosnu i= Â¼On Line Application formÂ½ vkeaf=r fd, tkrs gSaA vkosnd foKkfir ,d ;k ,d ls vf/kd lsokvksa ds fy, ,d gh vkosnu&i= izLrqr djsa %&\r\nfo''ks"k uksV%&\r\nÂ¼1Â½ On line Application Form esa leLr okafNr lwpuk vo''; vafdr djsaA dksbZ lwpuk xyr ;k viw.kZ Hkjus ij vH;FkhZ dk vkosnu jn~n dj mls ijh{kk esa izos''k ugha fn;k tk,xk ftldh ftEesnkjh Lo;a vkosnd dh gksxhA\r\nÂ¼2Â½ vkj{k.k dh fLFkfr ,oa fu;qfDr izfÃ?;k jkT; ljdkj ds funsZ''kkas ,oa uohure fu;eksa ds v/;/khu ifjorZuh; gksxhA\r\nÂ¼3Â½ vH;FkhZ inksa dh ojh;rk vkoâ??;d :i ls HkjsaA ,d ckj ojh;rk dze Hkjus ds iâ??pkr~ mlesa fdlh Hkh izdkj ls ifjorZu ugha fd;k tk;sxkA\r\n2- lsokokj fjDr inksa dk fooj.k %&\r\njkT; lsok,a Ã?- la- lsok dk uke osrueku dqy in\r\n1\r\njktLFkku iz''kklfud lsok\r\n15600-39100 GP 5400\r\n49\r\n2\r\njktLFkku iqfyl lsok\r\n15600-39100 GP 5400\r\n&\r\n3\r\njktLFkku ys[kk lsok\r\n15600-39100 GP 5400\r\n32\r\n4\r\njktLFkku lgdkjh lsok\r\n9300-34800 GP 4200\r\n1\r\n5\r\njktLFkku fu;kstu dk;kZy; lsok\r\n9300-34800 GP 4200\r\n4\r\n6\r\njktLFkku dkjkxkj lsok\r\n9300-34800 GP 4200\r\n3\r\n7\r\njktLFkku m|ksx lsok\r\n9300-34800 GP 4200\r\n5\r\n8\r\njktLFkku jkT; chek lsok\r\n15600-39100 GP 5400\r\n3\r\n9\r\njktLFkku okf.kfT;d dj lsok\r\n9300-34800 GP 4200\r\n39\r\n10\r\njktLFkku [kk| ,oa ukxfjd jln lsok\r\n9300-34800 GP 4200\r\n2\r\n11\r\njktLFkku i;ZVu lsok\r\n9300-34800 GP 4200\r\n7\r\n12\r\njktLFkku ifjogu lsok\r\n9300-34800 GP 4200\r\n2\r\n13\r\njktLFkku efgyk ,oa cky fodkl lsok\r\n15600-39100 GP 5400\r\n13\r\n14\r\njktLFkku nsoLFkku lsok\r\n9300-34800 GP 4200\r\n2\r\n15\r\njktLFkku xzkeh.k fodkl jkT; lsok\r\n15600-39100 GP 5400\r\n64\r\n16\r\njktLFkku efgyk fodkl lsok\r\n15600-39100 GP 5400\r\n7\r\ndqy in\r\n233\r\nv/khuLFk lsok,a Ã?- la- lsok dk uke osrueku dqy in\r\n1\r\njktLFkku v/khuLFk nsoLFkku lsok\r\n9300-34800 GP 3200\r\n15\r\n2\r\njktLFkku v/khuLFk lgdkjh lsok\r\n9300-34800 GP 3200\r\n&\r\n3\r\njktLFkku rglhynkj lsok\r\n9300-34800 GP 3600\r\n40\r\n4\r\njktLFkku vkcdkjh v/khuLFk lsok\r\n9300-34800 GP 3200\r\n13\r\n5\r\njktLFkku v/khuLFk lsok Â¼fu;kstuÂ½\r\n9300-34800 GP 3200\r\n&\r\n6\r\njktLFkku m|ksx v/khuLFk lsok\r\n9300-34800 GP 3600\r\n5\r\n7\r\njktLFkku okf.kfT;d dj v/khuLFk lsok\r\n9300-34800 GP 3200\r\n133\r\n8\r\njktLFkku [kk| ,oa ukxfjd jln v/khuLFk lsok\r\n9300-34800 GP 3200\r\n17\r\n9\r\njktLFkku efgyk ,oa cky fodkl v/khuLFk lsok\r\n9300-34800 GP 3600\r\n14\r\n10\r\njktLFkku lkekftd U;k; ,oa vf/kdkfjrk lsok\r\nÂ¼ifjoh{kk ,oa dkjkx`g dY;k.k vf/kdkjhÂ½\r\n9300-34800 GP 3600\r\n238\r\n11\r\njktLFkku lkekftd U;k; ,oa vf/kdkfjrk lsok\r\nÂ¼lkekftd lqj{kk vf/kdkjhÂ½\r\n9300-34800 GP 3600\r\n15\r\ndqy in\r\n490\r\nfoâ??ks"k uksV%& v/khuLFk lsokvksa dh dze la[;k 4]5]6 ,oa 7 ds inksa esa gh foHkkxh; deZpkfj;ksaa gsrq in vkjf{kr gSaA vr% bu vkjf{kr inksa gsrq lacaf/kr foHkkx esa dk;Zjr ea=kyf;d deZpkjh gh vkosnu djsa ,oa vkosnu&i= ds dkWye esa DC Â¼foHkkxh; deZpkjhÂ½ dk mYys[k voâ??; djsaA vU; vkosnd bu inksa gsrq DC ds dkWye dh iwfrZ ugha djsa A\r\nuksV %& 1 ''kklu ls fjDr inksa dk laâ??kksf/kr foLr`r oxhZdj.k izkIr gksus ij ;Fkk le; tkjh dj fn;k tk,xkA vkj{k.k dh fLFkfr ,oa fu;qfDr izfÃ?;k jkT; ljdkj ds funsZ''kkas ,oa uohure fu;eksa ds v/;/khu ifjorZuh; gksxhA\r\n2- mDr inksa dh visf{kr ''kS{kf.kd vgZrk ds vafre o"kZ esa lfEefyr gqvk gks ;k lfEefyr gksus okyk O;fDr Hkh vkosnu djus ds fy;s ik= gksxk] fdUrq mls eq[; ijh{kk esa lfEefyr gksus ls iwoZ ''kS{kf.kd vgZrk vftZr djus dk lcwr nsuk gksxk] vU;Fkk og vik= gksxkA\r\n3- vjktif=r deZpkfj;ksa gsrq vkjf{kr inksa ds lEcU/k esa %&\r\njkT; lsokvksa esa vjktif=r deZpkfj;ksa ds fy, vkjf{kr inksa ds fy, jktLFkku ljdkj] jktLFkku dh iapk;r lfefr;ksa ,oa ftyk ifj"knksa ds deZpkjh gh ik= gksaxsA vjktif=r deZpkjh ds ukrs ijh{kk esa Â¼jkT; lsokvksa esa muds fy, vkjf{kr inksa ds fy,Â½ cSBus gsrq vkosnd dks fuEu ''krsZa iw.kZ djuk pkfg, %&\r\nÂ¼[kÂ½ vuqHko %& fnukad 1 tuojh] 2014 dks fu;ekuqlkj iakp o"kZ ls vU;wu lsok] LFkkukiUu ;k vf/k"Bk;h :i ls iw.kZ gksuh pkfg,A\r\nuksV%& vkosnd dks fnukad 01-01-2014 dks lsok dk dqy fdruk vuqHko izkIr gS] mldk fnu] ekg o o"kZ dh iwfrZ fu/kkZfjr dkWye esa djsaA\r\nin o foHkkx in la[;k vk;q\r\njkT; lsok,a\r\n233\r\nvk;q %& fnukad 01-01-2014 dks U;wure 21 ,oa vf/kdre 35 ls deA\r\nvjktif=r deZpkjh fnukad 1 tuojh] 2014 dks 25 o"kZ dh vk;q izkIr dj pqdk gks ijUrq 45 o"kZ dk ugha gqvk gksA\r\nv/khuLFk lsok,a\r\n490\r\n''kS{kf.kd ;ksX;rk %& vkosnd dsUnz ;k Hkkjr ds fdlh jkT; fo/kku e.My ds fdlh vf/kfu;e }kjk fuxfer fdlh fo''ofo|ky; dh ;k laln ds fdlh vf/kfu;e }kjk LFkkfir ;k fo''ofo|ky; vuqnku vk;ksx vf/kfu;e] 1956 dh /kkjk 3 ds v/khu fo''ofo|ky; ds :i esa ?kksf"kr fdlh ''kSf{kd laLFkk dk mikf/k Â¼fMxzhÂ½ /kkjd gksuk pkfg, ;k vk;ksx ds ijke''kZ ls ljdkj }kjk ekU;rk izkIr dksbZ lerqY; vgZrk j[krk gksA\r\nijUrq ;g fd ikB~;Ã?e ds vfUre o"kZ dh ijh{kk] tks lh/kh HkrhZ ds fy, fu;eksa ;k vuqlwph esa ;Fkk mfYyf[kr in ds fy, visf{kr ''kSf{kd vgZrk gS]');

-- --------------------------------------------------------

--
-- Table structure for table `blogcomment`
--

CREATE TABLE IF NOT EXISTS `blogcomment` (
  `blogcid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comment` text NOT NULL,
  `blogc` int(11) NOT NULL,
  PRIMARY KEY (`blogcid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Dumping data for table `blogcomment`
--

INSERT INTO `blogcomment` (`blogcid`, `username`, `date`, `comment`, `blogc`) VALUES
(1, 'chandra', '2013-06-30 06:35:02', 'hello', 0),
(2, 'chandra', '2013-06-30 06:36:26', 'hello', 0),
(3, 'chandra', '2013-06-30 06:37:26', 'pankaj\r\n', 0);

-- --------------------------------------------------------

--
-- Table structure for table `comment`
--

CREATE TABLE IF NOT EXISTS `comment` (
  `commentid` int(11) NOT NULL AUTO_INCREMENT,
  `shareid` int(255) NOT NULL,
  `username` varchar(255) DEFAULT NULL,
  `date1` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comment` varchar(1000) DEFAULT NULL,
  `likes` int(11) DEFAULT NULL,
  PRIMARY KEY (`commentid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=23 ;

--
-- Dumping data for table `comment`
--

INSERT INTO `comment` (`commentid`, `shareid`, `username`, `date1`, `comment`, `likes`) VALUES
(3, 0, 'chandra', '2013-06-29 10:13:49', 'hello pankaj', 0),
(4, 0, 'chandra', '2013-06-29 10:21:54', 'hello', 0),
(5, 0, 'chandra', '2013-06-29 10:23:16', 'hello', 0),
(6, 0, 'chandra', '2013-06-29 10:26:04', 'hello paa', 0),
(8, 0, 'chandra', '2013-07-01 06:10:34', 'bad Monday :)', 0),
(9, 0, 'yash', '2013-07-02 08:08:59', 'jghjhk', 0),
(10, 0, 'yash', '2013-07-02 08:35:08', 'pankaj', 0),
(11, 0, 'yash', '2013-07-02 08:35:25', 'pankaj', 0),
(12, 0, 'yash', '2013-07-02 09:14:23', 'jkgakga', 0),
(13, 0, 'yash', '2013-07-02 09:22:34', 'asddgg', 0),
(14, 27, 'yash', '2013-07-02 11:18:56', NULL, 0),
(15, 27, 'yash', '2013-07-02 11:19:02', 'vkjvkj', 0),
(16, 27, 'yash', '2013-07-02 11:19:16', 'jkkjgkj', 0),
(17, 27, 'yash', '2013-07-02 11:21:00', 'pankaj\r\n', 0),
(18, 25, 'yash', '2013-07-02 11:31:06', 'hello pankaj', 0),
(19, 27, 'chandra', '2013-07-02 12:06:13', 'jgkkkkkkkkkkk', 0),
(20, 28, 'chandra', '2013-07-02 12:06:31', 'kczc', 0),
(21, 27, 'chandra', '2013-07-02 12:06:41', 'jkzxvzx', 0),
(22, 29, 'yash', '2013-07-02 17:22:17', 'pankaj', 0);

-- --------------------------------------------------------

--
-- Table structure for table `login`
--

CREATE TABLE IF NOT EXISTS `login` (
  `username` varchar(60) NOT NULL,
  `password` varchar(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `login`
--

INSERT INTO `login` (`username`, `password`) VALUES
('admin', 'chandra');

-- --------------------------------------------------------

--
-- Table structure for table `profile`
--

CREATE TABLE IF NOT EXISTS `profile` (
  `profileid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `pic` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `fname` varchar(255) DEFAULT NULL,
  `lname` varchar(255) DEFAULT NULL,
  `DOB` varchar(255) DEFAULT NULL,
  `sex` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `ccity` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `aboutme` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`profileid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=46 ;

--
-- Dumping data for table `profile`
--

INSERT INTO `profile` (`profileid`, `username`, `pic`, `email`, `fname`, `lname`, `DOB`, `sex`, `phone`, `ccity`, `country`, `address`, `website`, `aboutme`) VALUES
(26, 'ritesh', 'Hydrangeas.jpg', 'riteshaec10@gmail.com', 'ritesh', 'shrivastav', '13091993', NULL, '9198725123', 'agar', 'IN', 'basti', 'yashchandra.wordepress.com', 'hehehhehehehhehehe'),
(27, 'ritesh', 'Hydrangeas.jpg', 'riteshaec10@gmail.com', 'ritesh', 'shrivastav', '13091992', 'Male', '9198725123', 'agar', 'IN', 'baasti', 'yashchandra.wordepress.com', 'bdcsklvb'),
(28, 'ritesh', 'Hydrangeas.jpg', 'riteshaec10@gmail.com', 'ritesh', 'shrivastav', '13091974', 'Male', '9198725123', 'agar', 'IN', 'basti', 'yashchandra.wordepress.com', 'hjcjscnvj.cx'),
(37, 'yash', 'DSC_1374.JPG', 'pankaj9310@gmail.com', 'yash', 'Chaudhary', '13091993', 'Male', '8989931101', 'Jaipur', 'IN', 'basti', 'yashchandra.weebly.com', 'web disdeveloper'),
(38, 'yash', 'DSC_1374.JPG', 'pankaj9310@gmail.com', 'yash', 'Chaudhary', '201960', 'Male', '8989931101', 'Jaipur', 'IN', 'sjgsfjksf', 'yashchandra.weebly.com', 'sjkfksgf'),
(39, 'yash', 'DSC_1374.JPG', 'pankaj9310@gmail.com', 'yash', 'Chaudhary', '4071971', NULL, '8989931101', 'Jaipur', 'IN', 'basti', 'yashchandra.weebly.com', 'webdistoyerd'),
(40, 'chandra', 'Hydrangeas.jpg', 'pankajiiitm11@gmail.com', 'pankaj', 'chandra', '1301967', 'Male', '8957657315', 'Jaipur', 'IN', 'basti', 'yashchandra.weebly.com', 'haikhal '),
(41, 'yash', 'Koala.jpg', 'pankaj9310@gmail.com', 'yash', 'Chaudhary', 'DaysMonthsYears', NULL, '8989931101', 'Jaipur', '--', '', 'yashchandra.weebly.com', ''),
(42, 'yash', 'Penguins.jpg', 'pankaj9310@gmail.com', 'yash', 'Chaudhary', 'DaysMonthsYears', NULL, '8989931101', 'Jaipur', '--', '', 'yashchandra.weebly.com', ''),
(43, 'yash', 'Jellyfish.jpg', 'pankaj9310@gmail.com', 'yash', 'Chaudhary', 'DaysMonthsYears', NULL, '8989931101', 'Jaipur', '--', '', 'yashchandra.weebly.com', ''),
(44, 'yash', 'Penguins.jpg', 'pankaj9310@gmail.com', 'yash', 'Chaudhary', 'DaysMonthsYears', NULL, '8989931101', 'Jaipur', '--', '', 'yashchandra.weebly.com', ''),
(45, 'ritesh', 'Chrysanthemum.jpg', 'riteshaec10@gmail.com', 'ritesh', 'shrivastav', 'DaysMonthsYears', NULL, '9198725123', 'agar', '--', '', 'yashchandra.wordepress.com', '');

-- --------------------------------------------------------

--
-- Table structure for table `register`
--

CREATE TABLE IF NOT EXISTS `register` (
  `username` varchar(255) NOT NULL DEFAULT '',
  `password` varchar(60) DEFAULT NULL,
  `email` varchar(60) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `Login` varchar(255) DEFAULT NULL,
  `Flag` int(5) DEFAULT NULL,
  `Auth_code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`username`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `register`
--

INSERT INTO `register` (`username`, `password`, `email`, `phone`, `Login`, `Flag`, `Auth_code`) VALUES
('chandra', 'rYRaJKR97sv6g5bpDbdcag==', 'pankajiiitm11@gmail.com', '8965231470', 'user', 1, 'fwr2yuJYHJtw'),
('kissor', '68DiX18imIHA+DNTD4dENw==', 'phibersirhack@gmail.com', '9198725123', 'user', 0, 'fprnu38gHC5E'),
('pankaj', 'vKgTS4EN+N5/QpyjuIBZ6g==', 'pankaj9310@gmail.com', '8989931101', 'user', 1, 'RfW2Z2N6ZpvJ'),
('ritesh', 'ld61ARqP4cz2VSu1vNov8A==', 'riteshaec10@gmail.com', '7509812005', 'user', 1, 'MAEpRBzUxnW9'),
('yash', 'rYRaJKR97sv6g5bpDbdcag==', 'pankaj9310@gmail.com', '8989931101', 'user', 0, 'K3sphwFpSdF4');

-- --------------------------------------------------------

--
-- Table structure for table `share`
--

CREATE TABLE IF NOT EXISTS `share` (
  `shareid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `share` text,
  `status` int(11) NOT NULL,
  PRIMARY KEY (`shareid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=31 ;

--
-- Dumping data for table `share`
--

INSERT INTO `share` (`shareid`, `username`, `date`, `share`, `status`) VALUES
(15, 'pankaj', '2013-06-28 15:53:40', 'DBMS\r\nThe earlier query, using the left outer join with the on condition, includes a tuple (70557, Snow, Physics, 0, null, null, null, null, null, null ), because there is no tuple in takes with ID = 70557. In the latter query, however, every tuple satisfies the join condition true, so no null-padded tuples are generated by the outer join. The outer join actually generates the Cartesian product of the two relations. Since there is no tuple in takes with ID = 70557, every time a tuple appears in the outer join with name = Ã¢??SnowÃ¢??, the values for student.ID and takes.ID must be different, and such tuples would be eliminated by the where clause predicate. Thus student Snow never appears in the result of the latter query. The earlier query, using the left outer join with the on condition, includes a tuple (70557', 0),
(17, 'chandra', '2013-06-29 10:26:42', 'ffffffffffffffffffffffffffffffffff', 0),
(18, 'pankaj', '2013-06-30 09:58:02', 'happy sunday :)', 0),
(19, 'chandra', '2013-07-01 06:10:05', 'dhjdkffjdvldjvkdkdldl', 0),
(24, 'yash', '2013-07-02 08:35:32', 'jgadkjagkjgadjkg', 0),
(25, 'yash', '2013-07-02 09:22:46', 'sddfghyjj', 0),
(26, 'yash', '2013-07-02 09:22:49', '', 0),
(27, 'yash', '2013-07-02 09:23:03', 'jfgdlfgdkfgdkfdk', 0),
(28, 'chandra', '2013-07-02 12:06:03', 'jkgaaaaaaaaas', 0),
(29, 'yash', '2013-07-02 17:22:12', 'adlfksgfsfvshfvx.mlsgsif/sg.ks', 0),
(30, 'ritesh', '2013-07-02 17:25:28', 'gffhfhfh', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
